name: Build & Publish pdf.js

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: choice
        description: Release Type
        options: 
        - "patch"
        - "minor"
        - "major"

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./build/generic
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: '@certifyinc'
      - run: npm install -g gulp-cli
      - run: npm install
      - run: gulp generic
      - run: | 
          npm version ${{ github.event.inputs.name }}
          cd /home/runner/work/pdf.js/pdf.js/build/generic
          npm version ${{ github.event.inputs.name }}
          git config --global user.name 'cbillen-emburse'
          git config --global user.email 'connor.billen@emburse.com'
          git commit -am "Automated Build Commit"
          git push
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
