name: Build & Publish pdf.js

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: 'The version to bump the package to'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@certifyinc'

      - name: Install Gulp
        run: npm install -g gulp-cli

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: gulp generic

      - name: Bumping Package Version
        run: |
          cd build
          npm version ${{ github.event.inputs.version }}
          cp package.json generic/

      - name: Publishing Package
        run: |
          cd build/generic
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
