name: Build & Publish pdf.js

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: choice
        description: Release Type
        options: 
        - "patch"
        - "minor"
        - "major"

jobs:
  publish:
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./build/generic
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: '@certifyinc'
      - run: npm install -g gulp-cli
      - run: npm ci
      - run: gulp generic
      - name: Bumping Package Version
        run: |
          cd build
          npm version ${{ github.event.inputs.name }}
          cp package.json generic/
      - name: Committing Changes to Repo
        run: |
          git config --global user.name 'cbillen-emburse'
          git config --global user.email 'connor.billen@emburse.com'
          git add -A
          git commit -m "Automated Build Commit"
          git push
      - name: Publishing Package
        run: |
          cd build/generic
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
