name: Build & Publish pdf.js

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: choice
        description: Release Type
        options: 
        - "patch"
        - "minor"
        - "major"

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./build/generic
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: '@certifyinc'
      - run: |
          npm install
          npm build
          npm version ${{ github.event.inputs.name }}
          cd ./build/generic
          npm version ${{ github.event.inputs.name }}
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
